
import "./globals.css";
import SessionProviderWrapper from "./SessionProviderWrapper";
import Navbar from "@/components/Navbar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SessionProviderWrapper>
      <Navbar /> 
      {children}</SessionProviderWrapper>
      </body>
    </html>
  );
}
